// <auto-generated />
namespace TamFinansCase.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BookRefactoring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookRefactoring));
        
        string IMigrationMetadata.Id
        {
            get { return "202206032011038_BookRefactoring"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
